### PR TITLE
Add optional desktop notifications for incoming messages

### PR DESCRIPTION
**Pull request by geomaster**
This PR adds a `notify` option in the config JSON file, which, if set to true, enables desktop notifications for incoming Slack messages. The notifications will have the channel the message originates from in the title, and the message content in the text.

**Rationale:** Since I'm running slack-term in a separate gnome-terminal tab (not using screen/tmux), I'd like to somehow be notified when new messages arrive. The aim is to avoid running Slack in the browser as I've found that switching terminal tabs is less disruptive to my workflow than switching to a browser window and then tab. Further, the Slack desktop app is Electron-based and consumes ridiculous amounts of memory, so I'm avoiding running it too. However, when running slack-term only, I'm not notified of new messages as they arrive, which is an important feature for me that both the web and desktop clients provide.

**Implementation details:** The library used is [`0xAX/notificator`](https://github.com/0xAX/notificator), which seems to support Windows, Linux and OS X via different backends. I've tested only on Linux, and everything appears to be working smoothly. It'd be helpful if someone could test on these other systems. For more detailed info about the changes, see the body of the commits included in the PR.

### CODE REVIEW

**Comment by kim0** [comment]
@erroneousboat .. I hope we can get this merged soon. Notification support is the only thing stopping me for leaving bloated slack behind

**Comment by Voronenko** [comment]
I have two questions

1) Potentially - do we have on roadmap switching from legacy tokens to API ? Not all channel owners are keen to to issue legacy tokens ( reasoning : they can be used to gather emails, althouth I can do the same just having access to their slack's room websocket uri :)))))

2) That notifications in GUI would be very helpful. I have configured in tmux "agressive" colors for panes with notifications, but GUI popup would be a way more helpful.

**Comment by geomaster** [comment]
@erroneousboat Would you please give a reasoning on why this PR was closed? If there are any problems with it, I'm happy to fix them.

**Comment by erroneousboat** [comment]
It has been implemented in [v0.4.0](https://github.com/erroneousboat/slack-term/releases/tag/v0.4.0
)

#116
4b4a0cb5f49794240e6ac39190d10bffe62f7fc1

**Pull request closed without merging**
